name: packaging
on:
  - push
jobs:
  format:
    name: check-formating
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
         python-version: "3.11"
      - name: install tox
        run: python -m pip install tox

      - name: Run black
        run: tox -e format
