name: My first workflow
on:
  - push
jobs:
  say-hello:
    name: say-hello
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: say say-hello
        run: echo "hello"